### ISSUE TITLE
BeagleBone Black 6.0.1 build error

### ISSUE THREAD

**Issue by sivareddycn46** [csimmonds/android4beagle#2]
Hi 

I'm building android 6.0.1 for beaglebone but I got the following error.  

=================================================================
java -Xmx3500m -jar out/host/linux-x86/framework/jill.jar  --output out/target/common/obj/JAVA_LIBRARIES/sdk_v19_intermediates/classes.jack.tmpjill.jack prebuilts/sdk/19/android.jar
Launching background server java -Dfile.encoding=UTF-8 -Xms2560m -XX:+TieredCompilation -jar out/host/linux-x86/framework/jack-launcher.jar -cp out/host/linux-x86/framework/jack.jar com.android.jack.server.JackSimpleServer
Launching background server java -Dfile.encoding=UTF-8 -Xms2560m -XX:+TieredCompilation -jar out/host/linux-x86/framework/jack-launcher.jar -cp out/host/linux-x86/framework/jack.jar com.android.jack.server.JackSimpleServer
Launching background server java -Dfile.encoding=UTF-8 -Xms2560m -XX:+TieredCompilation -jar out/host/linux-x86/framework/jack-launcher.jar -cp out/host/linux-x86/framework/jack.jar com.android.jack.server.JackSimpleServer
Launching background server java -Dfile.encoding=UTF-8 -Xms2560m -XX:+TieredCompilation -jar out/host/linux-x86/framework/jack-launcher.jar -cp out/host/linux-x86/framework/jack.jar com.android.jack.server.JackSimpleServer
out/host/linux-x86/bin/jack: line 131: 29977 Killed                  $SERVER_PRG $SERVER_PORT_SERVICE $SERVER_PORT_ADMIN $SERVER_COUNT $SERVER_NB_COMPILE $SERVER_TIMEOUT >> $SERVER_LOG 2>&1
ERROR: Cannot launch Jack server
ERROR: Cannot launch Jack server
ERROR: Cannot launch Jack server
ERROR: Cannot launch Jack server
make: *** [out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack] Error 255
make: *** Deleting file `out/target/common/obj/JAVA_LIBRARIES/sdk_v20_intermediates/classes.jack'
make: *** Waiting for unfinished jobs....
make: *** [out/target/common/obj/JAVA_LIBRARIES/sdk_v19_intermediates/classes.jack] Error 255
make: *** Deleting file `out/target/common/obj/JAVA_LIBRARIES/sdk_v19_intermediates/classes.jack'
make: *** [out/target/common/obj/JAVA_LIBRARIES/sdk_v21_intermediates/classes.jack] Error 255
make: *** Deleting file `out/target/common/obj/JAVA_LIBRARIES/sdk_v21_intermediates/classes.jack'
make: *** [out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/with-local/classes.dex] Error 41
ERROR
=======================================================================

pls solve above error to build code

**Comment by csimmonds** [comment]
Well, the problem is with your Jack server configuration, so please double check your Java version. Also, Jack does not perform well if you don't have enough memory. For Marshmallow, you need *at least* 8 GB RAM.

**Comment by sivareddycn46** [comment]
Thank you
