### ISSUE TITLE
Time out with Repo Sync for 4 repositories 

### ISSUE THREAD

**Issue by mikegoettling** [csimmonds/android4beagle#4]
hello 
I am having an issue when trying to sync the repositories for Beagal board black and it is happening with all 3 android branches. im getting time outs with the below repositories and I am a novice when it comes to linux. I have googled but to no luck finding an answer. below are the time outs. i am running Ubuntu server 22.04 repo is 2.32 Python is version 3.10.6  \

mike@bbbandroid:~/a4b$ repo sync -c -j20
Fetching: 51% (236/460) Last synced: platform/packages/wallpapers/NoiseField
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'

device/lge/hammerhead:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'
device/lge/hammerhead: sleeping 4.0 seconds before retrying
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'

device/lge/hammerhead:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'
error: Cannot fetch device/lge/hammerhead from https://android.googlesource.com/device/lge/hammerhead

fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'

platform/external/dexmaker:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'
platform/external/dexmaker: sleeping 4.0 seconds before retrying
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'

platform/external/dexmaker:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'
error: Cannot fetch platform/external/dexmaker from https://android.googlesource.com/platform/external/dexmaker
Fetching: 98% (452/460) Last synced: platform/external/mesa3d
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

ti-linux-kernel-dev:
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

ti-linux-kernel-dev: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

ti-linux-kernel-dev:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

a4b-scripts:
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

a4b-scripts: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

a4b-scripts:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

error: Cannot fetch ti-linux-kernel-dev from git://github.com/RobertCNelson/ti-linux-kernel-dev
error: Cannot fetch a4b-scripts from git://github.com/csimmonds/a4b-scripts

fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Connection timed out

a4b-beagleboneblack:
fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Connection timed out

a4b-beagleboneblack: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

a4b-beagleboneblack:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Connection timed out

u-boot:
fatal: unable to connect to github.com:
github.com[0: 140.82.114.4]: errno=Connection timed out

u-boot: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

u-boot:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed outerror: Cannot fetch a4b-beagleboneblack from git://github.com/csimmonds/a4b-beagleboneblack

error: Cannot fetch u-boot from git://github.com/csimmonds/u-boot
Fetching: 100% (460/460), done in 8m53.572s
Fetching:  0% (0/6) warming up
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

a4b-beagleboneblack:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

a4b-beagleboneblack: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

a4b-beagleboneblack:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out
error: Cannot fetch a4b-beagleboneblack from git://github.com/csimmonds/a4b-beagleboneblack

fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

ti-linux-kernel-dev:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Connection timed out

ti-linux-kernel-dev: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

ti-linux-kernel-dev:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out
error: Cannot fetch ti-linux-kernel-dev from git://github.com/RobertCNelson/ti-linux-kernel-dev

fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'

device/lge/hammerhead:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'
device/lge/hammerhead: sleeping 4.0 seconds before retrying
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'

device/lge/hammerhead:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/device/lge/hammerhead.git'
error: Cannot fetch device/lge/hammerhead from https://android.googlesource.com/device/lge/hammerhead

fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'

platform/external/dexmaker:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'
platform/external/dexmaker: sleeping 4.0 seconds before retrying
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'

platform/external/dexmaker:
fatal: not a git repository: '/home/mike/a4b/.repo/projects/external/dexmaker.git'
error: Cannot fetch platform/external/dexmaker from https://android.googlesource.com/platform/external/dexmaker

fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

u-boot:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

u-boot: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

u-boot:
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out
error: Cannot fetch u-boot from git://github.com/csimmonds/u-boot
Fetching: 33% (2/6) Last synced: u-boot
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

a4b-scripts:
fatal: unable to connect to github.com:
github.com[0: 140.82.113.3]: errno=Connection timed out

a4b-scripts: sleeping 4.0 seconds before retrying
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out

a4b-scripts:
fatal: unable to connect to github.com:
github.com[0: 140.82.112.4]: errno=Connection timed out
error: Cannot fetch a4b-scripts from git://github.com/csimmonds/a4b-scripts
Fetching: 100% (6/6), done in 8m58.443s
error: Cannot checkout ti-linux-kernel-dev: ManifestInvalidRevisionError: revision refs/tags/4.1.30-ti-r70 in ti-linux-kernel-dev not found
error: in `sync -c -j20`: revision refs/tags/4.1.30-ti-r70 in ti-linux-kernel-dev not found

**Comment by csimmonds** [comment]
The problem is that github no longer support unencrypted Git protocol (https://github.blog/2021-09-01-improving-git-protocol-security-github/), and so repo sync was not able to get repositories from "a4b" and "rcn" remotes

The solution is to use https instead. I have made this change to the manifest (default.xml) on all branches, so the problem is resolved

**Comment by mikegoettling** [comment]
sorry i'm not that versed in Linux.

is that something that has to be changed in the default xml for 
4.4.4_r2  i did repo with

|repo init -u https://github.com/csimmonds/android4beagle -b 
android-4.4.4_r2 |

**Comment by csimmonds** [comment]
@mikegoettling I have made the changes to all branches, you just need to start again from the repo init stage

**Comment by mikegoettling** [comment]
Thanks i got that working now on all 3 builds. getting below issue when 
building 4.4r2  will try build with the other versions but need to 
change java to 1.7

scripts/kconfig/conf --silentoldconfig Kconfig
   CHK     include/linux/version.h
   CC      scripts/mod/empty.o
   HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x30): multiple 
definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first 
defined here
collect2: error: ld returned 1 exit status
make[2]: *** [scripts/Makefile.host:127: scripts/dtc/dtc] Error 1
make[1]: *** [scripts/Makefile.build:441: scripts/dtc] Error 2
make[1]: *** Waiting for unfinished jobs....
   MKELF   scripts/mod/elfconfig.h
   HOSTCC  scripts/mod/file2alias.o
   HOSTCC  scripts/mod/modpost.o
   HOSTCC  scripts/mod/sumversion.o
   CHK     include/generated/utsrelease.h
make[1]: 'include/generated/mach-types.h' is up to date.
   CC      kernel/bounds.s
   GEN     include/generated/bounds.h
   CC      arch/arm/kernel/asm-offsets.s
   HOSTLD  scripts/mod/modpost
make: *** [Makefile:506: scripts] Error 2
make: *** Waiting for unfinished jobs....
   GEN     include/generated/asm-offsets.h
   CALL    scripts/checksyscalls.sh
ERROR
***@***.***:~/android4$ ./build-beagleboneblack.sh
